import { StudyPlan, AssistantMode, QuizData, FlashcardDeck, SyllabusImportResult, GeneratedSyllabusTask } from '../types';

export interface GeneratePlanParams {
  studentName?: string;
  subject: string;
  topics?: string;
  topicList?: string[];
  examDate?: string;
  daysAvailable?: number;
  hoursPerDay?: number;
  difficulty?: string;
  topicDifficulty?: string;
  dailyTarget?: string;
  preferredTime?: string;
  notes?: string;
}

export interface SyllabusToTasksParams {
  pdfBase64?: string;
  mimeType?: string;
  text?: string;
  studentName?: string;
  subjectHint?: string;
  daysAvailable?: number;
  hoursPerDay?: number;
  difficulty?: string;
  examDate?: string;
}

export interface AssistantRequestParams {
  mode: AssistantMode;
  subject?: string;
  input: string;
  query?: string;
  options?: any;
}

export interface AssistantResponse {
  result: string | QuizData | FlashcardDeck;
  isFallback?: boolean;
  message?: string;
  errorNotice?: string;
}

export const AIService = {
  // Generate Tasks and Schedule directly from Syllabus PDF / Text
  async generateTasksFromSyllabus(params: SyllabusToTasksParams): Promise<SyllabusImportResult> {
    try {
      const response = await fetch('/api/ai/syllabus-to-tasks', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(params),
      });

      if (!response.ok) {
        throw new Error(`Server responded with ${response.status}: ${response.statusText}`);
      }

      const data: SyllabusImportResult = await response.json();
      return data;
    } catch (err: any) {
      console.warn('AI Syllabus Parser fetch error, building client syllabus tasks fallback', err);
      return createClientFallbackSyllabusResult(params);
    }
  },

  // Generate Study Plan (Dedicated AI Study Planner Engine)
  async generateStudyPlan(params: GeneratePlanParams): Promise<{ plan: StudyPlan; isFallback: boolean; errorNotice?: string }> {
    try {
      const response = await fetch('/api/ai/planner', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(params),
      });

      if (!response.ok) {
        throw new Error(`Server returned ${response.status}: ${response.statusText}`);
      }

      const data = await response.json();
      const planData = data.plan;
      const topicsStr = Array.isArray(params.topicList) && params.topicList.length > 0
        ? params.topicList.join(', ')
        : (params.topics || '');

      const fullPlan: StudyPlan = {
        id: 'plan-' + Date.now(),
        studentName: params.studentName || planData.studentName || 'Student',
        title: planData.title || `${params.subject} Master Study Blueprint`,
        subject: params.subject,
        topics: topicsStr,
        topicList: params.topicList || (topicsStr ? topicsStr.split(/[,;\n]+/).map(t => t.trim()).filter(Boolean) : []),
        examDate: params.examDate || planData.examDate || 'In 3 weeks',
        daysAvailable: params.daysAvailable || planData.daysAvailable || 14,
        hoursPerDay: params.hoursPerDay || planData.hoursPerDay || 3,
        dailyTarget: params.dailyTarget || planData.dailyTarget || 'Cover 1 core topic + 5 practice problems',
        difficultyLevel: (params.difficulty as any) || planData.difficultyLevel || 'Intermediate',
        preferredTime: (params.preferredTime as any) || planData.preferredTime || 'Evening',
        summary: planData.summary || 'Custom study plan generated by FocusGuard AI.',
        recommendedDailyMinutes: planData.recommendedDailyMinutes || (params.hoursPerDay || 3) * 60,
        projectedReadinessScore: planData.projectedReadinessScore || 85,
        topicPriorities: planData.topicPriorities || [],
        dailySchedule: planData.dailySchedule || [],
        weeklyPlan: planData.weeklyPlan || [],
        revisionSchedule: planData.revisionSchedule || [],
        practiceSchedule: planData.practiceSchedule || [],
        examPreparationStrategy: planData.examPreparationStrategy || [],
        createdAt: new Date().toISOString(),
        completedTaskIds: [],
      };

      return {
        plan: fullPlan,
        isFallback: !!data.isFallback,
        errorNotice: data.errorNotice,
      };
    } catch (err: any) {
      console.warn('AI Planner fetch failed, using smart offline fallback generator', err);
      // Generate client-side fallback
      const fallback = createClientFallbackPlan(params);
      return {
        plan: fallback,
        isFallback: true,
        errorNotice: 'AI service is currently unavailable. Switched to offline study planner engine.',
      };
    }
  },

  // Call AI Study Assistant
  async askAssistant(params: AssistantRequestParams): Promise<AssistantResponse> {
    try {
      const response = await fetch('/api/ai/assistant', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(params),
      });

      if (!response.ok) {
        throw new Error(`Server returned ${response.status}: ${response.statusText}`);
      }

      const data = await response.json();
      return {
        result: data.result,
        isFallback: !!data.isFallback,
        message: data.message,
        errorNotice: data.errorNotice,
      };
    } catch (err: any) {
      console.warn('AI Assistant request failed, using client fallback', err);
      return {
        result: getClientAssistantFallback(params),
        isFallback: true,
        errorNotice: 'AI service is currently offline. Showing local knowledge base response.',
      };
    }
  },

  // AI Task Breakdown Helper
  async generateSubtasks(title: string, subject?: string): Promise<{ subtasks: { id: string; title: string; completed: boolean }[]; estimatedMinutes: number }> {
    try {
      const res = await this.askAssistant({
        mode: 'chat',
        subject: subject || 'Study Task',
        input: `Break down this study task into 3-4 concrete actionable subtasks with estimated time: "${title}". Return JSON format.`,
      });

      // Default smart fallback generator if AI returns text or fails
      return generateHeuristicSubtasks(title);
    } catch {
      return generateHeuristicSubtasks(title);
    }
  },
};

function generateHeuristicSubtasks(title: string): { subtasks: { id: string; title: string; completed: boolean }[]; estimatedMinutes: number } {
  const lower = title.toLowerCase();
  let subtasks: { id: string; title: string; completed: boolean }[] = [];
  let estimatedMinutes = 45;

  if (lower.includes('assignment') || lower.includes('project') || lower.includes('homework')) {
    subtasks = [
      { id: 'st-1', title: 'Review rubric and gather formulas/materials', completed: false },
      { id: 'st-2', title: 'Solve problems / write draft implementation', completed: false },
      { id: 'st-3', title: 'Double check calculations and citations', completed: false },
      { id: 'st-4', title: 'Format and submit final version', completed: false },
    ];
    estimatedMinutes = 90;
  } else if (lower.includes('exam') || lower.includes('quiz') || lower.includes('midterm') || lower.includes('test')) {
    subtasks = [
      { id: 'st-1', title: 'Review lecture slides and formula cheat sheet', completed: false },
      { id: 'st-2', title: 'Solve 5-10 past exam questions under time pressure', completed: false },
      { id: 'st-3', title: 'Log errors in revision notebook', completed: false },
      { id: 'st-4', title: 'Self-test with active recall flashcards', completed: false },
    ];
    estimatedMinutes = 60;
  } else {
    subtasks = [
      { id: 'st-1', title: 'Read core theory and synthesize main points', completed: false },
      { id: 'st-2', title: 'Work through 3 standard practice examples', completed: false },
      { id: 'st-3', title: 'Write 1-page condensed summary note', completed: false },
    ];
    estimatedMinutes = 45;
  }

  return { subtasks, estimatedMinutes };
}

function createClientFallbackPlan(params: GeneratePlanParams): StudyPlan {
  const topicsArray = Array.isArray(params.topicList) && params.topicList.length > 0
    ? params.topicList
    : (params.topics || '').split(/[,;\n]+/).map((t) => t.trim()).filter(Boolean);
  const hrs = Number(params.hoursPerDay || 3);
  const days = Number(params.daysAvailable || 14);
  const sub = params.subject || 'Academic Subject';
  const name = params.studentName || 'Student';
  const mainTopics = topicsArray.length > 0 ? topicsArray : ['Core Concepts', 'Applied Problems', 'Final Review'];

  return {
    id: 'plan-' + Date.now(),
    studentName: name,
    title: `${sub} Master Exam Preparation Blueprint`,
    subject: sub,
    topics: mainTopics.join(', '),
    topicList: mainTopics,
    examDate: params.examDate || 'In 3 weeks',
    daysAvailable: days,
    hoursPerDay: hrs,
    dailyTarget: params.dailyTarget || 'Cover 1 core topic + 5 practice problems',
    difficultyLevel: (params.difficulty as any) || 'Intermediate',
    preferredTime: (params.preferredTime as any) || 'Evening',
    summary: `Structured ${hrs}h daily study regimen tailored for ${name} at ${params.difficulty || 'Intermediate'} level in ${sub}. Designed with spaced repetition to guarantee test readiness by ${params.examDate || 'target date'}.`,
    recommendedDailyMinutes: hrs * 60,
    projectedReadinessScore: 86,
    topicPriorities: mainTopics.map((t, idx) => ({
      topic: t,
      priority: idx === 0 ? 'High' : idx === 1 ? 'High' : 'Medium',
      difficulty: (params.topicDifficulty as any) || (idx === 0 ? 'Medium' : idx === 1 ? 'Hard' : 'Easy'),
      estimatedHours: Math.max(2, Math.round((hrs * 6) / (mainTopics.length || 1))),
      urgencyReason: idx === 0 ? 'High exam weightage & prerequisite theory' : 'Standard core topic',
      keyConcepts: [`${t} Core Definitions`, `Applied Problems in ${t}`, `Formula Applications`],
    })),
    dailySchedule: [
      {
        dayNumber: 1,
        dayTitle: `Day 1: Concept Mastery in ${mainTopics[0] || sub}`,
        date: 'Day 1',
        timeSlot: `${params.preferredTime || 'Evening'} (${hrs} Hours)`,
        focusTarget: 'Master fundamental definitions and formulas',
        sessions: [
          {
            time: 'Session 1 (50m)',
            topic: mainTopics[0] || sub,
            activity: 'Active Concept Reading & Note Condensing',
            goal: 'Extract key formulas and definition summary',
            durationMinutes: 50,
          },
          {
            time: 'Session 2 (45m)',
            topic: mainTopics[0] || sub,
            activity: 'Step-by-step Worked Examples',
            goal: 'Solve 4 standard test questions',
            durationMinutes: 45,
          },
          {
            time: 'Session 3 (25m)',
            topic: 'Review',
            activity: 'Flashcard Self-Testing',
            goal: 'Reinforce memory before sleeping',
            durationMinutes: 25,
          },
        ],
      },
      {
        dayNumber: 2,
        dayTitle: `Day 2: ${mainTopics[1] || mainTopics[0] || sub} Problem Sets`,
        date: 'Day 2',
        timeSlot: `${params.preferredTime || 'Evening'} (${hrs} Hours)`,
        focusTarget: 'Solve intermediate questions and analyze error patterns',
        sessions: [
          {
            time: 'Session 1 (50m)',
            topic: mainTopics[1] || mainTopics[0] || sub,
            activity: 'Deep Problem Solving',
            goal: 'Complete 6 exercises without notes',
            durationMinutes: 50,
          },
          {
            time: 'Session 2 (40m)',
            topic: 'Review & Error Log',
            activity: 'Analyse Mistakes & Review Tricky Steps',
            goal: 'Update red notebook error log',
            durationMinutes: 40,
          },
        ],
      },
      {
        dayNumber: 3,
        dayTitle: `Day 3: Advanced Application & Recall`,
        date: 'Day 3',
        timeSlot: `${params.preferredTime || 'Evening'} (${hrs} Hours)`,
        focusTarget: 'Cross-topic synthesis and spaced review',
        sessions: [
          {
            time: 'Session 1 (50m)',
            topic: mainTopics[2] || mainTopics[0] || sub,
            activity: 'Mixed Exam Problems',
            goal: 'Solve timed practice questions',
            durationMinutes: 50,
          },
          {
            time: 'Session 2 (30m)',
            topic: 'Spaced Flashcards',
            activity: 'Active recall sprint on Day 1 & Day 2 topics',
            goal: 'Verify zero conceptual decay',
            durationMinutes: 30,
          },
        ],
      },
    ],
    weeklyPlan: [
      {
        weekNumber: 1,
        theme: 'Theory Mastery & Flashcard Creation',
        milestone: 'Complete 100% of theory reading and base problems',
        deliverables: ['Summary sheets created', '20 sample questions solved'],
      },
      {
        weekNumber: 2,
        theme: 'Intermediate Problem Solving & Weak-Area Remediation',
        milestone: 'Solve timed sectional tests',
        deliverables: ['Mock test 1', 'Flashcards reviewed twice'],
      },
      {
        weekNumber: 3,
        theme: 'Full Exam Simulations & Spaced Review',
        milestone: 'Achieve 85%+ on timed mock exam',
        deliverables: ['2 Full past papers under timed conditions', 'Formula review'],
      },
    ],
    revisionSchedule: [
      { stage: 'Day 1', method: '10-minute active recall self-quiz', timing: 'End of study block' },
      { stage: 'Day 3', method: 'Solve 5 practice problems from memory', timing: '48h later' },
      { stage: 'Day 7', method: 'Flashcard sprint & mind mapping', timing: 'End of week' },
      { stage: 'Day 14', method: 'Timed mock test simulation', timing: 'Pre-exam week' },
    ],
    practiceSchedule: [
      { phase: 'Phase 1: Diagnostic', recommendedResource: 'End-of-chapter quiz', targetScore: '75%+' },
      { phase: 'Phase 2: Timed Drills', recommendedResource: 'Past exam sectional problems', targetScore: '85%+' },
      { phase: 'Phase 3: Full Simulation', recommendedResource: 'Past 3 years official exam papers', targetScore: '90%+' },
    ],
    examPreparationStrategy: [
      'Maintain an active Error Log to review tricky questions daily.',
      'Always time practice questions at 1.5 minutes per mark.',
      'Stop cramming 24 hours before the exam; prioritize sleep and confidence.',
    ],
    createdAt: new Date().toISOString(),
    completedTaskIds: [],
  };
}

function getClientAssistantFallback(params: AssistantRequestParams): string | QuizData | FlashcardDeck {
  if (params.mode === 'quiz' || params.mode === 'mcq') {
    return {
      title: `Practice Assessment: ${params.subject || 'Study Subject'}`,
      totalQuestions: 3,
      questions: [
        {
          id: 'q1',
          question: `What is the most effective approach to mastering "${params.input.slice(0, 40)}"?`,
          options: [
            'A. Active recall through flashcards and practice problems',
            'B. Re-reading the same textbook section 5 times passively',
            'C. Highlighting without solving any questions',
            'D. Cramming everything 2 hours before the exam',
          ],
          correctIndex: 0,
          explanation: 'Active recall forces your brain to retrieve information, building stronger synaptic pathways.',
          difficulty: 'Easy',
        },
        {
          id: 'q2',
          question: 'What is the core recommendation of the Spaced Repetition technique?',
          options: [
            'A. Review only once right before tests',
            'B. Review material at increasing intervals (Day 1, 3, 7, 14)',
            'C. Study for 12 hours with zero breaks',
            'D. Memorize answers without understanding the logic',
          ],
          correctIndex: 1,
          explanation: 'Spaced intervals counteract the forgetting curve and transfer knowledge to long-term memory.',
          difficulty: 'Medium',
        },
        {
          id: 'q3',
          question: 'When stuck on a difficult exam problem, what should you do first?',
          options: [
            'A. Give up and leave it completely blank',
            'B. State knowns, target variable, and applicable formula to claim partial marks',
            'C. Pick a random choice immediately',
            'D. Erase all your prior work',
          ],
          correctIndex: 1,
          explanation: 'Systematic setup ensures partial credit and often unlocks the solution path.',
          difficulty: 'Easy',
        },
      ],
    };
  }

  if (params.mode === 'flashcards') {
    return {
      deckTitle: `Flashcards: ${params.subject || 'Core Concepts'}`,
      cards: [
        {
          id: 'c1',
          front: `Definition of ${params.input.slice(0, 35)}`,
          back: 'The governing theoretical mechanism that maps input parameters into measurable outcomes.',
          hint: 'Think foundational rule',
        },
        {
          id: 'c2',
          front: 'Feynman Learning Technique',
          back: 'Explaining a complex idea simply, as if teaching a beginner, to uncover conceptual blind spots.',
          hint: 'Simple plain English explanation',
        },
        {
          id: 'c3',
          front: 'Spaced Repetition intervals',
          back: 'Day 1 (immediate), Day 3 (reinforce), Day 7 (consolidate), Day 14 (mastery).',
          hint: 'Exponential spacing',
        },
      ],
    };
  }

  if (params.mode === 'summarize') {
    return `### 📌 Study Summary: ${params.subject || 'Topic'}\n\n- **Overview:** Systematic deconstruction of "${params.input}".\n- **Core Principle:** Focus on key formulas and problem-solving derivations.\n- **Exam Strategy:** Solve past-year numericals to verify conceptual retention.\n- **Quick Takeaway:** Active recall beats passive reading every time!`;
  }

  return `### 💡 FocusGuard Study Tutor\n\nRegarding **"${params.input}"**:\n\n1. **Core Concept:** Break this topic into small, manageable chunks.\n2. **Active Practice:** Explain the main idea in 2 sentences in your own words.\n3. **Exam Test:** Solve at least 3 practice questions to cement your understanding.\n\nLet me know if you want me to generate an **interactive quiz** or **flashcard deck**!`;
}

function createClientFallbackSyllabusResult(params: SyllabusToTasksParams): SyllabusImportResult {
  const days = Number(params.daysAvailable || 14);
  const hrs = Number(params.hoursPerDay || 3);
  const rawText = params.text || '';
  const lines = rawText.split('\n').map(l => l.trim()).filter(Boolean);

  let detectedSubject = params.subjectHint || 'Academic Syllabus Course';
  for (const line of lines.slice(0, 8)) {
    if (/^(Course|Subject|Module|Topic|Paper|Class)\s*[:\-]/i.test(line)) {
      detectedSubject = line.replace(/^(Course|Subject|Module|Topic|Paper|Class)\s*[:\-]\s*/i, '').trim();
      break;
    } else if (line.length > 3 && line.length < 50 && !line.startsWith('-') && !line.startsWith('Unit')) {
      detectedSubject = line;
      break;
    }
  }

  const generatedTasks: GeneratedSyllabusTask[] = [];
  const today = new Date();
  const sampleModules = [
    { title: 'Unit 1: Core Fundamentals & Theory', topics: ['Definitions and core theorems', 'Essential mechanisms and axioms'] },
    { title: 'Unit 2: Problem Solving & Numerical Applications', topics: ['Standard question patterns', 'Formulas and step-by-step algorithms'] },
    { title: 'Unit 3: Advanced Topics & Edge Cases', topics: ['Multi-concept synthesis', 'Past exam high-weightage sections'] },
    { title: 'Unit 4: Final Revision & Mock Exam Drill', topics: ['Formula cheat sheet review', 'Timed past papers'] },
  ];

  sampleModules.forEach((mod, idx) => {
    const dayOffset = Math.min(days - 1, Math.floor((idx / sampleModules.length) * days));
    const targetDate = new Date(today);
    targetDate.setDate(targetDate.getDate() + dayOffset);
    const dateStr = targetDate.toISOString().split('T')[0];

    generatedTasks.push({
      id: `task-syl-c-${idx + 1}`,
      title: `${mod.title} - Comprehensive Study & Notes`,
      category: idx === 0 ? 'Study' : idx === 1 ? 'Assignment' : idx === 2 ? 'Study' : 'Exam Prep',
      priority: idx === 0 || idx === 3 ? 'High' : 'Medium',
      estimatedMinutes: 60,
      dueDate: dateStr,
      subject: detectedSubject,
      moduleName: mod.title,
      notes: mod.topics.join('; ') + '. Focus on active recall and clean notes.',
      subtasks: [
        { id: `st-${idx}-1`, title: 'Read syllabus chapter and formulate notes', completed: false },
        { id: `st-${idx}-2`, title: 'Solve 5 foundational practice problems', completed: false },
        { id: `st-${idx}-3`, title: 'Complete self-assessment checklist', completed: false },
      ],
      selected: true,
    });
  });

  return {
    subject: detectedSubject,
    courseCode: 'ACAD-SYL',
    overview: `Syllabus analyzed across ${sampleModules.length} core units and ${generatedTasks.length} study tasks spanning ${days} days.`,
    totalEstimatedHours: days * hrs,
    modules: sampleModules.map((m, i) => ({
      unitNumber: i + 1,
      unitTitle: m.title,
      topics: m.topics,
      estimatedHours: Math.max(3, Math.round((days * hrs) / sampleModules.length)),
      weightagePercentage: 25,
      difficulty: 'Medium',
    })),
    tasks: generatedTasks,
    isFallback: true,
    errorNotice: 'Parsed using FocusGuard offline curriculum engine.',
  };
}

